import { svgAssets } from './svgAssets';
import { assetCallbacks } from './callbacks';
import { globals } from './globals';

export const i18n: Record<string, Record<string, string>> = {
  en: {
    rotatePrompt: "Rotate and enter full screen?",
    rotateInstruction: "Please physically rotate your device to landscape mode.",
    flow: "FLOW",
    expLvl: "EXP Lvl",
    btnDash: "DASH",
    btnSlash: "SLASH",
    btnEnhance: "ENHANCE",
    btnUlt: "ULT",
    death: "DEATH",
    tryAgain: "Try Again",
    levelUp: "LEVEL UP!",
    chooseUlt: "CHOOSE ULTIMATE",
    title: "SUPER<br>SAMURAI<br>STICKY",
    play: "Play",
    settings: "Settings",
    settingsTitle: "SETTINGS",
    musicVol: "Music Volume",
    language: "Language",
    back: "Back",
    paused: "PAUSED",
    activeUpgradesTitle: "ACTIVE UPGRADES",
    guideTitle: "Combat Guide & Techniques",
    guideMove: "<strong>Movement:</strong> Use <strong>WASD / Arrow Keys</strong> on Desktop, or the <strong>Virtual Joystick</strong> on Mobile devices to move around the battlefield.",
    guideSlash: "<strong>Slash (Basic Attack):</strong> Left-click / press <strong>LMB</strong> on Desktop or tap <strong>SLASH</strong> on Mobile. Attacks automatically auto-aim to track nearest enemies. Chain kills quickly to stack your Combo meter.",
    guideDodge: "<strong>Dodge / Dash:</strong> Press <strong>SPACEBAR</strong> on Desktop or tap <strong>DASH</strong> on Mobile. You are completely invulnerable (i-frames) during the dash duration.",
    guidePerfect: "<strong>Perfect Dodge:</strong> Dash exactly when an enemy starts their red lunge attack to trigger a screen flash, a massive Combo boost, and 2 seconds of total invulnerability.",
    guideFlow: "<strong>Flow Awakening (Ultimates):</strong> Defeat enemies to fill the orange FLOW meter. When full, press <strong>F Key</strong> (or tap <strong>ULT</strong> on Mobile) to select and trigger a devastating Ultimate:<br>• <strong>Shadow Awakening:</strong> 6 seconds of god-speed. Basic attacks gain +4 DMG, spawn shadow clones that teleport and strike enemies for 4 DMG, and dash cooldown is reduced to 0.<br>• <strong>Omnislash:</strong> Freezes time for 3.5s, executing 3 cross-cuts dealing 16 DMG each to all enemies, followed by a final blast dealing 20 DMG to remaining enemies, restoring 2 Hearts.<br>• <strong>Wrath of the Storm God:</strong> 8 seconds of electric fury. Slashes fire chain-lightning to 4 targets. Dashes become instant teleports (450px) that strike start and destination coordinates with vertical lightning (6 DMG, 3s stun, chains to 5 targets for 2 DMG).",
    guideProg: "<strong>Progression & Leveling:</strong> Gain EXP from kills to level up. Leveling up heals 1 Heart and grants a choice between powerful upgrades (like Cooldown Reductions, Max HP, or unique passives like Soul Siphon for life-steal and Reflective Mirror to boost deflected bullets).",
    guideParry: "<strong>Parrying:</strong> Hold down SLASH to charge your sword, and release it at the exact moment of an incoming enemy attack to Parry, deflecting the blow and staggering the enemy.",
    guideIaijutsu: "<strong>Iaijutsu Shockwave:</strong> Holding down SLASH charges your attack. Release it at full charge to unleash a traveling crescent shockwave projectile that pierces through all enemies.",
    guideAutoAim: "<strong>Auto-Aim:</strong> Basic slashes and lunges will automatically snap toward the closest target within 600px range, making high-speed mobile combat feel extremely smooth.",
    guidePvP: "<strong>Iaijutsu PvP:</strong> Enter the PvP Lobby, copy your unique 8-digit Ronin UID, add friends by their UID, and invite them directly to a 1v1 duel. No code sharing required!",
    comboSwift: "<strong>Combo — Swift Counter:</strong> Press <strong>SLASH</strong> immediately after <strong>DASH</strong>. Teleports behind the nearest enemy for a lightning-fast backstab.",
    comboThunder: "<strong>Combo — Thunderclap & Flash:</strong> Press <strong>SLASH</strong> immediately after <strong>DASH</strong> while <strong>Wrath of the Storm God</strong> is active or with <strong>Raijin Step</strong> skill equipped. Slashes through targets with chain-lightning.",
    comboDragon: "<strong>Combo — Rising Dragon:</strong> <strong>SLASH → SLASH → hold SLASH briefly → release early</strong> (before full charge). Launches enemies skyward with an uppercut shockwave.",
    comboMirror: "<strong>Combo — Mirror Strike:</strong> Perform a fully charged <strong>Iaijutsu Slash</strong> while invisible (from the <strong>Reflective Mirror / Decoy</strong> passive). Summons twin phantom clones that strike all nearby enemies.",
    resume: "Resume Game",
    quit: "Quit to Menu",
    kills: "Kills: ",
    combo: " Combo",
    dashText: "DASH!",
    dodgeText: "PERFECT DODGE!",
    parryText: "PARRY!",
    perfectParryText: "PERFECT PARRY!",
    iaijutsuText: "IAIJUTSU!",
    levelUpText: "LEVEL UP!",
    swordEnhancedText: "SWORD ENHANCED!",
    puGiantName: "Giant Katana", puGiantDesc: "Slash Size +25%",
    puWindName: "Wind Stance", puWindDesc: "Attack Cooldown -15%",
    puFeatherName: "Feather Step", puFeatherDesc: "Dash Cooldown -25%",
    puSwiftName: "Swiftness", puSwiftDesc: "Movement Speed +20%",
    puBloodName: "Bloodlust", puBloodDesc: "Flow Generation +30%",
    puLethalName: "Lethal Strike", puLethalDesc: "Enhance Bonus Dmg +1",
    puColossalName: "Colossal Blade", puColossalDesc: "Enhance Size +50%",
    puDurationName: "Divine Scroll", puDurationDesc: "Enhance Duration +1.5s",
    puShieldDurationName: "Aegis Mastery", puShieldDurationDesc: "Wind Aegis duration +1.5s",
    puShieldPulseName: "Hurricane Pulse", puShieldPulseDesc: "Wind Aegis releases wind pulses dealing 3 DMG every 1s",
    puShieldBlastName: "Gale Thorns", puShieldBlastDesc: "While Wind Aegis is active, melee attackers take 8 DMG + knockback per level",
    puDashDamageName: "Storm Bolt", puDashDamageDesc: "Raijin Step deals +1 DMG and stuns for 2.0s",
    puDashRangeName: "Static Velocity", puDashRangeDesc: "Raijin Step range +30% and speed +20%",
    puDashThunderName: "Lightning Chain", puDashThunderDesc: "Raijin Step chains lightning to 3 nearby enemies dealing 2 DMG per level",
    puFirewheelRangeName: "Searing Ring", puFirewheelRangeDesc: "Inferno Sweep radius +25%",
    puFirewheelBlazeName: "Searing Ash", puFirewheelBlazeDesc: "Inferno Sweep burn damage +1",
    puFirewheelEchoName: "Firestorm Echo", puFirewheelEchoDesc: "Sweep hits trigger a 1 DMG spark explosion on nearby enemies",
    puGravityRadiusName: "Event Horizon", puGravityRadiusDesc: "Gravity Well pull radius +25%",
    puGravityDamageName: "Crushing Force", puGravityDamageDesc: "Gravity Well pull tick damage +1",
    puGravityExplosionName: "Supernova Collapse", puGravityExplosionDesc: "Gravity Well implodes upon expiration, dealing 4 DMG per level in a massive blast",
    puChargeSpeedName: "Lightning Draw", puChargeSpeedDesc: "Iaijutsu Charge speed +35%",
    puDeflectDmgName: "Reflective Mirror", puDeflectDmgDesc: "Deflected bullets deal +2 DMG",
    puVampireName: "Soul Siphon", puVampireDesc: "Kills have 6% chance to heal 1 Heart",
    puDimensionalName: "Dimensional Rift", puDimensionalDesc: "Iaijutsu wave size +30%",
    puFireName: "Fire Stance", puFireDesc: "Slashes burn enemies (1 DMG/s for 3s)",
    puClonesName: "Shadow Clones", puClonesDesc: "Translucent shadow clones mimic attacks",
    puStoutHeartName: "Stout Heart", puStoutHeartDesc: "Max Hearts limit +1 Slot (max 7)",
    puPetalArmorName: "Petal Armor", puPetalArmorDesc: "Blocks 1 hit (recharges every 15s)",
    puEchoSlashName: "Echo Slash", puEchoSlashDesc: "Slashes emit secondary waves dealing 0.5 DMG",
    puTempoMasteryName: "Tempo Mastery", puTempoMasteryDesc: "+2% attack speed per combo level (max 20%)",
    puFrostName: "Frost Stance", puFrostDesc: "Slashes apply Chill (slows enemies by 40% for 3s). Parrying a chilled enemy shatters them for 8 AoE damage.",
    puVoidName: "Void Stance", puVoidDesc: "Iaijutsu Shockwaves leave a spatial trail that pulls nearby enemies toward its center.",
    puFlowingCounterName: "Flowing Counter", puFlowingCounterDesc: "Successfully parrying or dodging an attack instantly resets your Dash/Raijin Step cooldown.",
    puGaleVortexName: "Gale Vortex", puGaleVortexDesc: "Aegis duration is reduced by 1s, but shield rotates at triple speed and reflects all bullets directly back at the shooters.",
    puBladeEchoesName: "Blade Echoes", puBladeEchoesDesc: "Flow Awakening spawns two permanent shadow clones flanking you, mimicking attacks at 40% DMG and double size.",
    puJudgementCutName: "Judgement Cut", puJudgementCutDesc: "Fully charged Iaijutsu waves spawn a dome of 6 rapid micro-slices dealing 0.5 DMG each over 1.5s.",
    puSakuraBlizzardName: "Sakura Blizzard", puSakuraBlizzardDesc: "Dashing leaves cherry blossom petals that explode for 1 DMG when enemies step on them.",
    puUnstableOverloadName: "Unstable Overload", puUnstableOverloadDesc: "Dashing through a chilled or burning enemy triggers a 5 DMG elemental explosion.",
    puMagneticDrawName: "Magnetic Draw", puMagneticDrawDesc: "Automatically pulls EXP gems and Hearts toward you from a wide radius.",
    puReapersMarkName: "Reaper's Mark", puReapersMarkDesc: "Slashes deal +2 DMG, but you lose 1 Heart every 25s. Defeating 10 enemies resets this timer.",
    skillDecoyName: "Shadow Step / Decoy", skillDecoyDesc: "Spawns 2 decoys that slash for 3 DMG and detonate for 8 DMG + 1.5s stun on death. Grants invisibility & +50% speed for 5s. Cooldown 14s.",
    btnDecoy: "SHADOW",
    ultShadowName: "Shadow Awakening", ultShadowDesc: "6s of god-speed. Slashes deal +4 DMG and spawn clones that teleport-strike enemies. Dash cooldown becomes 0.",
    ultOmniName: "Omnislash", ultOmniDesc: "Freeze time for 3.5s to execute 3 cross-cuts (16 DMG). Final blast deals 20 DMG and heals 2 Hearts.",
    ultStormName: "Wrath of the Storm God", ultStormDesc: "8s of thunder fury. Slashes fire chain lightning. Dashes teleport 450px and call lightning strikes (6 DMG, 3s stun).",
    playZen: "Zen Mode",
    zenWarningText: "PARRY ONLY!",
    zenFieldText: "ZEN FIELD",
    btnParryOnly: "PARRY ONLY",
    btnRestricted: "RESTRICTED",
    puZenRestoreName: "Zen Recovery", puZenRestoreDesc: "Restore 1 Heart slot.",
    ultZenFieldName: "Zen Field", ultZenFieldDesc: "Summon a Zen Barrier that blocks all incoming damage and triggers wind parry blasts (6 AoE DMG + knockback) every 0.4s for 8s.",
    blessingSwiftName: "Swift Strike Stance",
    blessingFortuneName: "Fortune Blessing",
    loading: "LOADING RESOURCES",
    tapToContinue: "TAP / CLICK TO CONTINUE",
    fsPromptText: "Enter full screen mode for the best samurai experience?",
    statsTitle: "DEATH SUMMARY",
    statsKills: "KILLS:",
    statsMaxCombo: "MAX COMBO:",
    statsParries: "TOTAL PARRIES:",
    statsPerfectParries: "PERFECT PARRIES:",
    statsPerfectDodges: "PERFECT DODGES:",
    statsDamage: "DAMAGE DEALT:",
    graphicsMode: "Graphics",
    difficulty: "Difficulty",
    difficultyEasy: "Easy",
    difficultyNormal: "Normal",
    difficultyHard: "Hard",
    difficultyInsane: "Insane",
    playTime: "Time Mode",
    playLevel: "Level Mode",
    timeLimit: "Time Limit",
    timeInfinite: "Infinite",
    targetLevel: "Target Level",
    victory: "VICTORY",
    timeModeCompleted: "TIME SURVIVED!",
    levelModeCompleted: "TARGET LEVEL REACHED!",
    guideDifficulty: "<strong>Difficulty Modes:</strong> Select your challenge before starting.<br>• <strong>Easy:</strong> Enemies have 30% HP, move 50% slower, charge 80% slower, and spawn in smaller waves.<br>• <strong>Normal:</strong> Enemies have 50% HP, move 30% slower, charge 40% slower.<br>• <strong>Hard:</strong> Enemies have 130% HP, move 15% faster, charge 25% faster, and spawn in larger/faster waves.<br>• <strong>Insane:</strong> 3x harder than Hard. Enemies have 300% HP, move 55% faster, charge 150% faster, and spawn in massive, aggressive waves.",
    selectSkillTitle: "SELECT ACTIVE SKILL",
    skillEnhanceName: "Dragon's Fury", skillEnhanceDesc: "Sword size +80%, DMG +3 for 10s, and slashes fire huge crescent waves. Cooldown 18s.",
    skillShieldName: "Wind Aegis", skillShieldDesc: "Deflects bullets, grants invulnerability & +40% speed for 5.5s, pulsing to deal DMG and pull in enemies. Cooldown 14s.",
    skillDashName: "Raijin Step", skillDashDesc: "Lightning dash dealing 3 DMG and 1.8s stun, summoning lightning bolts on start and end. Cooldown 2.8s.",
    skillFirewheelName: "Inferno Sweep", skillFirewheelDesc: "Spins fire ring dealing 4 DMG every 0.3s, burning enemies and shooting rotating fireballs for 5s. Cooldown 12s.",
    skillGravityName: "Gravity Well", skillGravityDesc: "Pulls in enemies, dealing 2 DMG every 0.3s, devouring enemy bullets. Implodes for 6 DMG. Cooldown 13s.",
    skillParryMasterName: "Parry Master", skillParryMasterDesc: "Allows you to parry enemy attacks automatically by pressing attack for 5s. Cooldown 16s.",
    btnShield: "AEGIS",
    btnFlash: "RAIJIN",
    btnFirewheel: "SWEEP",
    btnGravity: "GRAVITY",
    btnParryMaster: "PARRY",
    screenShakeMode: "Screen Shake",
    shakeOn: "Standard",
    shakeReduced: "Reduced",
    shakeOff: "Off",
    autoUlt: "Flow Auto Activation",
    autoUltOn: "On",
    autoUltOff: "Off",
    screenFlash: "Screen Flash/Invert",
    weatherEffects: "Weather & Petals",
    speedLines: "Speed Lines",
    floatingText: "Floating Numbers",
    groundScars: "Ground Slash Marks",
    settingsOn: "On",
    settingsOff: "Off",
    pvpLobbyTitle: "IAIJUTSU SHOWDOWN",
    pvpMyProfile: "MY PROFILE",
    pvpLoadingRonin: "Loading Ronin...",
    pvpSave: "Save",
    pvpUidDisplay: "UID: Loading...",
    pvpCopy: "Copy",
    pvpSelectRules: "SELECT GAME RULES",
    pvpClassicDuel: "CLASSIC DUEL (3 Lives)",
    pvpSuddenDeath: "SUDDEN DEATH (1 Life, Fast Start)",
    pvpHyperSpeed: "HYPER SPEED (3 Lives, Rapid Acceleration)",
    pvpStormGod: "STORM GOD (3 Lives, Sky Lightning Storms)",
    pvpCoopSurvival: "INSANE CO-OP SURVIVAL (Insane Difficulty, AI Waves)",
    pvpSuddenDeathShort: "SUDDEN DEATH",
    pvpHyperSpeedShort: "HYPER SPEED",
    pvpStormGodShort: "STORM GOD",
    pvpCoopSurvivalShort: "CO-OP SURVIVAL",
    pvpFindMatch: "Find Match",
    pvpCancelQueue: "Cancel Queue",
    pvpSearching: "Searching for opponents... ",
    pvpFoundConnecting: "Opponent found! Connecting...",
    pvpFriends: "Friends",
    pvpRequests: "Requests",
    pvpTopDuelists: "Top Duelists",
    pvpAddFriend: "ADD FRIEND",
    pvpFriendUidPlaceholder: "Paste Friend UID...",
    pvpAdd: "Add",
    pvpNoFriends: "No friends added yet. Share your UID!",
    pvpPendingRequests: "PENDING REQUESTS",
    pvpNoRequests: "No pending requests.",
    pvpNoRecords: "No records yet.",
    pvpLoadingLeaderboard: "Loading leaderboard...",
    pvpBackToMenu: "Back to Menu",
    pvpReadyRoomMode: "MODE: ",
    pvpHost: "Host (P1)",
    pvpClient: "Client (P2)",
    pvpWaiting: "WAITING",
    pvpReady: "READY",
    pvpReadyUp: "Ready Up",
    pvpCancelReady: "Cancel Ready",
    pvpDisconnect: "Disconnect",
    pvpDuelChallenge: "DUEL CHALLENGE!",
    pvpDecline: "Decline",
    pvpAccept: "Accept",
    pvpDefendTimedParry: "DEFEND: TIMED PARRY!",
    pvpWaitingForOpponent: "WAITING FOR OPPONENT...",
    pvpYourTurn: "YOUR TURN: CHARGE [HOLD SLASH]",
    pvpParryLockout: "PARRY LOCKOUT!",
    pvpWins: "WINS!",
    pvpRematch: "Rematch",
    pvpRematchStatus: "Rematch? ({count}/2 Ready)",
    pvpQuitToMenu: "Quit to Menu",
    pvpRound: "ROUND",
    pvpReadyText: "READY...",
    pvpRally: "RALLY:",
    pvpSpeed: "Speed",
    pvpKills: "KILLS",
    pvpConnecting: "CONNECTING...",
    pvpConnected: "CONNECTED",
    pvpError: "ERROR",
    pvpOnline: "ONLINE",
    pvpChallengeMsg: "{name} has challenged you to a duel!",
    pvpInvite: "Invite",
    
    // Alert strings
    alertUidCopied: "Your UID has been copied to clipboard!",
    alertFailedToConnect: "Failed to connect: ",
    alertOpponentDisconnected: "Opponent disconnected. Returning to main menu.",
    alertConnectionClosed: "Connection closed by remote peer.",
    alertFailedUpdateName: "Failed to update display name: ",
    alertProfileNameUpdated: "Profile name updated successfully!",
    alertFriendReqAccepted: "Friend request accepted!",
    alertFailedAcceptReq: "Failed to accept request: ",
    alertFriendReqDeclined: "Friend request declined.",
    alertFailedDeclineReq: "Failed to decline request: ",
    alertEnterValidUid: "Please enter a valid 8-digit numeric UID.",
    alertCannotAddSelf: "You cannot add yourself as a friend.",
    alertUidNotFound: "Ronin UID not found.",
    alertAlreadyFriends: "You are already friends with this Ronin.",
    alertFailedAddFriend: "Failed to add friend: ",
    alertFriendReqSent: "Friend request sent to {name}!",
    alertFailedRemoveFriend: "Failed to remove friend: ",
    alertFriendRemoved: "Friend removed successfully.",
    alertDuelInviteDeclined: "Your duel invitation was declined.",
    alertFailedInviteFriend: "Failed to invite friend: ",
    alertMatchmakingFailed: "Matchmaking connection failed: ",
    alertFailedMatchmaking: "Failed to enter matchmaking: "
  },
  ja: {
    rotatePrompt: "画面を回転して全画面表示にしますか？",
    rotateInstruction: "デバイスを横向き（ランドスケープ）に回転させてください。",
    flow: "気 (FLOW)",
    expLvl: "レベル",
    btnDash: "回避",
    btnSlash: "斬る",
    btnEnhance: "強化",
    btnUlt: "奥義",
    death: "死",
    tryAgain: "もう一度",
    levelUp: "レベルアップ！",
    chooseUlt: "奥義を選択",
    title: "スーパー<br>サムライ<br>スティッキー",
    play: "プレイ",
    settings: "設定",
    settingsTitle: "設定",
    musicVol: "音楽の音量",
    language: "言語",
    back: "戻る",
    paused: "一時停止",
    activeUpgradesTitle: "強化アビリティ",
    guideTitle: "戦闘ガイド＆テクニック",
    guideMove: "<strong>移動:</strong> パソコンでは<strong>WASD / 矢印キー</strong>、モバイルでは<strong>仮想ジョイスティック</strong>を使用して戦場を自由に移動できます。",
    guideSlash: "<strong>斬撃 (基本攻撃):</strong> パソコンでは左クリック(<strong>LMB</strong>)、モバイルでは<strong>攻撃ボタン</strong>をタップします。攻撃は最も近い敵へ自動でホーミングします。連続キルでコンボ数を重ねましょう。",
    guideDodge: "<strong>回避 (ダッシュ):</strong> パソコンでは<strong>スペースキー</strong>、モバイルでは<strong>回避ボタン</strong>を押します。ダッシュ中は完全無敵 (無敵フレーム) となります。",
    guidePerfect: "<strong>ジャスト回避:</strong> 敵が赤く光って突進する瞬間にダッシュを合わせると、画面がフラッシュし、コンボゲージが大幅に上昇して2秒間の無敵シールドを獲得します。",
    guideFlow: "<strong>気の覚醒 (奥義):</strong> 敵を倒してオレンジ色の気（FLOW）ゲージを溜めます。満タン時に<strong>Fキー</strong>（モバイルでは<strong>奥義ボタン</strong>）を押すと、以下のいずれかの強力な奥義を選択・発動できます：<br>• <strong>影の覚醒:</strong> 10秒間の神速状態。通常攻撃のダメージが+4され、敵に瞬間移動して4ダメージを与える影分身を生成。ダッシュのクールダウンが0になります。<br>• <strong>超究武神覇斬:</strong> 3.5秒間時間を停止し、全敵に16ダメージの交差斬りを3回実行。最後に残った敵に20ダメージの爆風を放ち、ライフを2回復。<br>• <strong>雷神の稲妻:</strong> 8秒間の雷撃状態。通常斬撃から4体に連鎖する雷撃を放つ。さらにダッシュが瞬間移動（450px）になり、開始地点と終点に縦の稲妻（6ダメージ、3秒気絶、5体へ2ダメージの連鎖）を落とします。",
    guideProg: "<strong>成長とアップグレード:</strong> 敵を撃破してEXPを溜め、レベルアップします。レベルアップ時は体力が1回復し、各種能力強化に加え、確率で体力を吸収する「吸魂の刃」や跳ね返し弾を強化する「反射の鏡」などの固有能力を選択できます。",
    guideParry: "<strong>受け流し (パリィ):</strong> 攻撃ボタンを長押しして力を溜め、敵の攻撃が当たる瞬間に離すことで、敵の攻撃を完璧に弾き返して無効化し、相手をよろめかせることができます。",
    guideIaijutsu: "<strong>居合・真空波:</strong> 攻撃ボタンを長押しでチャージし、最大チャージ時に離すことで、前方の敵を全て貫通する超高速の「三日月型真空波」を放ちます。",
    guideAutoAim: "<strong>自動エイム:</strong> 通常攻撃や踏み込みは、範囲600px以内の最も近い敵へ自動的に照準を合わせるため、高機動な戦闘を直感的に楽しめます。",
    guidePvP: "<strong>居合・対戦モード:</strong> PvPロビーに入り、独自のRonin UIDをコピーして友人を追加し、直接1v1の居合決闘に招待できます。一時的なルームコードの共有は不要です！",
    comboSwift: "<strong>コンボ — 疾風カウンター:</strong> <strong>ダッシュ</strong>直後に<strong>斬撃</strong>を押す。最も近い敵の背後に瞬間移動して一閃。",
    comboThunder: "<strong>コンボ — 雷光一閃:</strong> <strong>雷神の稲妻</strong>発動中、または<strong>雷神ステップ</strong>スキル装備時に<strong>ダッシュ</strong>直後に<strong>斬撃</strong>を押す。雷撃を纏って敵を斬り裂く。",
    comboDragon: "<strong>コンボ — 昇竜撃:</strong> <strong>斬撃 → 斬撃 → 斬撃を少し溜めて早めに離す</strong>（フルチャージ前）。衝撃波で敵を空中へ打ち上げる。",
    comboMirror: "<strong>コンボ — 鏡像一閃:</strong> <strong>反射の鏡／デコイ</strong>パッシブの透明化中にフルチャージの<strong>居合斬り</strong>を放つ。双子の幻影分身が全ての近くの敵を攻撃する。",
    resume: "ゲーム再開",
    quit: "タイトルへ",
    kills: "撃破数: ",
    combo: " コンボ",
    dashText: "回避！",
    dodgeText: "ジャスト回避！",
    parryText: "弾き！",
    perfectParryText: "ジャスト弾き！",
    iaijutsuText: "居合斬り！",
    levelUpText: "レベルアップ！",
    swordEnhancedText: "刀強化！",
    puGiantName: "巨大な刀", puGiantDesc: "斬撃サイズ +25%",
    puWindName: "風の型", puWindDesc: "攻撃クールダウン -15%",
    puFeatherName: "羽の歩み", puFeatherDesc: "ダッシュクールダウン -25%",
    puSwiftName: "迅速", puSwiftDesc: "移動速度 +20%",
    puBloodName: "血の渇き", puBloodDesc: "気（フロー）の生成 +30%",
    puLethalName: "致命撃", puLethalDesc: "強化時の追加ダメージ +1",
    puColossalName: "巨大剣", puColossalDesc: "強化時のサイズ +50%",
    puDurationName: "神の巻物", puDurationDesc: "強化持続時間 +1.5秒",
    puShieldDurationName: "風神の領域", puShieldDurationDesc: "風の加護の持続時間 +1.5秒",
    puShieldPulseName: "烈風の波動", puShieldPulseDesc: "風の加護発動中、1秒ごとに周囲の敵へ3ダメージの波動を放つ",
    puShieldBlastName: "暴風の棘", puShieldBlastDesc: "風 of 加護発動中、近接攻撃を受けると敵にレベル毎8ダメージ＋吹き飛ばし",
    puDashDamageName: "迅雷の猛撃", puDashDamageDesc: "雷神の瞬歩のダメージ +1、気絶時間 2.0秒に延長",
    puDashRangeName: "静電気の加速", puDashRangeDesc: "雷神の瞬歩の間合い +30%、速度 +20%",
    puDashThunderName: "連鎖雷撃", puDashThunderDesc: "雷神の瞬歩命中時、周囲3体の敵にレベル毎2ダメージの連鎖雷撃",
    puFirewheelRangeName: "焦熱の炎輪", puFirewheelRangeDesc: "業火の回天の範囲 +25%",
    puFirewheelBlazeName: "猛烈な残り火", puFirewheelBlazeDesc: "業火の回天の炎上ダメージ +1",
    puFirewheelEchoName: "火炎の残響", puFirewheelEchoDesc: "命中すると周囲の敵に1ダメージを与える爆発火花を誘発",
    puGravityRadiusName: "事象の地平線", puGravityRadiusDesc: "重力崩壊の引き寄せ範囲 +25%",
    puGravityDamageName: "圧砕する斥力", puGravityDamageDesc: "重力崩壊の継続ダメージ +1",
    puGravityExplosionName: "超新星爆発", puGravityExplosionDesc: "重力崩壊終了時に爆縮が起き、レベル毎に4ダメージを与える",
    puChargeSpeedName: "迅雷 of 構え", puChargeSpeedDesc: "居合チャージ速度 +35%",
    puDeflectDmgName: "反射 of 鏡", puDeflectDmgDesc: "跳ね返し弾の威力 +2 DMG",
    puVampireName: "吸魂 of 刃", puVampireDesc: "撃破時に6%の確率でハート回復",
    puDimensionalName: "次元 of 裂け目", puDimensionalDesc: "真空波のサイズ +30%",
    puFireName: "火 of 型", puFireDesc: "斬撃が敵を炎上させ、3秒間継続ダメージ(1 DMG/秒)を与える",
    puClonesName: "影分身 of 術", puClonesDesc: "攻撃を模倣する分身を召喚する",
    puStoutHeartName: "不屈 of 心", puStoutHeartDesc: "最大ハート数が1スロット増加（最大7）",
    puPetalArmorName: "桜花 of 鎧", puPetalArmorDesc: "敵の攻撃を1回防ぐ（15秒ごとに再チャージ）",
    puEchoSlashName: "残響 of 斬撃", puEchoSlashDesc: "斬撃から0.5の追加ダメージを与える真空波を放つ",
    puTempoMasteryName: "脈動 of 覇気", puTempoMasteryDesc: "コンボ数に応じて攻撃速度が上昇（最大20%）",
    puFrostName: "氷結の構え", puFrostDesc: "斬撃が敵を3秒間40%減速。氷結した敵を弾くと破裂して周囲に8ダメージ。",
    puVoidName: "虚無 of 構え", puVoidDesc: "居合斬りの衝撃波が周囲の敵を引き寄せる空間の裂け目を残す。",
    puFlowingCounterName: "受け流し of 極意", puFlowingCounterDesc: "弾き／回避成功時に瞬歩／雷神の瞬歩のクールダウンを即座にリセット。",
    puGaleVortexName: "疾風 of 渦", puGaleVortexDesc: "守護 of 防壁の時間が1秒減少するが、回転速度が3倍になり、すべての弾丸を自動照準で射手に反射する。",
    puBladeEchoesName: "刃 of 残影", puBladeEchoesDesc: "明鏡止水（アルティメット）中、上下に2体の分身が出現し、2倍サイズ・40%ダメージで攻撃を模倣。",
    puJudgementCutName: "次元斬", puJudgementCutDesc: "最大チャージの居合波の先に、1.5秒間で計6回（各0.5ダメージ）の高速微細斬撃を繰り出すドームを展開する。",
    puSakuraBlizzardName: "桜花吹雪", puSakuraBlizzardDesc: "ダッシュ時に足元に桜の花びらを残す。敵が踏むと爆発して1ダメージを与える。",
    puUnstableOverloadName: "不確実な過負荷", puUnstableOverloadDesc: "Chill（氷結）またはBurn（炎上）状態の敵をすり抜けるようにダッシュすると、5ダメージの範囲属性爆発が発生する。",
    puMagneticDrawName: "磁気引き寄せ", puMagneticDrawDesc: "広範囲からEXPジェムとハートを自動的にプレイヤーの元へ引き寄せる。",
    puReapersMarkName: "死神の刻印", puReapersMarkDesc: "通常斬撃の威力が+2されるが、25秒ごとにハートが1減少する。敵を10体倒すとこのタイマーがリセットされる。",
    skillDecoyName: "影遁・幻影の術", skillDecoyDesc: "5秒間姿を消し速度+50%。3ダメの通常攻撃を行い死亡時に8ダメ＆1.5秒気絶の爆発を起こす分身を2体召喚。クールダウン14秒。",
    btnDecoy: "影遁",
    ultShadowName: "影 of 覚醒", ultShadowDesc: "6秒間の神速移動状態。攻撃ダメージ+4かつ自動追撃の影分身を生成し、ダッシュのクールダウンを0にする。",
    ultOmniName: "超究武神覇斬", ultOmniDesc: "3.5秒間時間停止し、16ダメージの交差斬り3回。最後の爆発で全敵に20ダメージを与えハートを2回復。",
    ultStormName: "雷神の稲妻", ultStormDesc: "8秒間の雷撃状態。通常攻撃で連鎖雷撃。ダッシュは瞬間移動になり、開始点・終点に稲妻（6 DMG、3秒気絶）を召喚。",
    playZen: "禅・受け流し",
    zenWarningText: "受け流しのみ！",
    zenFieldText: "明鏡止水",
    btnParryOnly: "受け流しのみ",
    btnRestricted: "制限中",
    puZenRestoreName: "精神統一", puZenRestoreDesc: "体力を1回復する。",
    ultZenFieldName: "明鏡止水", ultZenFieldDesc: "被ダメージを無効化し、0.4秒毎に周囲に衝撃波（6範囲ダメージ＋押し出し）を放つ「禅の結界」を8秒間展開する。",
    blessingSwiftName: "神速の構え",
    blessingFortuneName: "招福の加護",
    loading: "リソース読み込み中",
    tapToContinue: "画面をタップ / クリックして開始",
    fsPromptText: "快適なプレイのために全画面（フルスクリーン）モードにしますか？",
    statsTitle: "戦績サマリー",
    statsKills: "撃破数:",
    statsMaxCombo: "最大コンボ:",
    statsParries: "弾き回数:",
    statsPerfectParries: "ジャスト弾き:",
    statsPerfectDodges: "ジャスト回避:",
    statsDamage: "与ダメージ:",
    graphicsMode: "画質設定",
    difficulty: "難易度",
    difficultyEasy: "イージー",
    difficultyNormal: "ノーマル",
    difficultyHard: "ハード",
    difficultyInsane: "インセイン",
    playTime: "タイムアタック",
    playLevel: "レベルアタック",
    timeLimit: "制限時間",
    timeInfinite: "無限",
    targetLevel: "目標レベル",
    victory: "完全勝利",
    timeModeCompleted: "生存時間達成！",
    levelModeCompleted: "目標レベル到達！",
    guideDifficulty: "<strong>難易度モード:</strong> 開始前に難易度を選択します。<br>• <strong>イージー:</strong> 敵の体力30%、速度50%減、チャージ80%遅、スポーン数少。<br>• <strong>ノーマル:</strong> 敵の体力50%、速度30%減、チャージ40%遅。<br>• <strong>ハード:</strong> 敵の体力130%、速度15%増、チャージ25%高速で、スポーン数が多く間隔も短いです。<br>• <strong>インセイン:</strong> ハードの3倍の難しさ。敵の体力300%、速度55%増、チャージ150%高速で、スポーン数が非常に多く間隔も極小です。",
    selectSkillTitle: "アクティブスキル選択",
    skillEnhanceName: "竜の激昂", skillEnhanceDesc: "10秒間、剣のサイズ+80%、ダメージ+3。さらに攻撃から巨大真空波を放つ。クールダウン18秒。",
    skillShieldName: "烈風 of 加護", skillShieldDesc: "5.5秒間、無敵＆速度+40%。敵の弾を反射する風の盾を展開し、周囲の敵を引き寄せダメージを与える。クールダウン14秒。",
    skillDashName: "雷神の瞬歩", skillDashDesc: "3ダメージ＆1.8秒気絶の雷光突進。開始と終了時に縦の稲妻を召喚する。クールダウン2.8秒。",
    skillFirewheelName: "業火の回天", skillFirewheelDesc: "5秒間、0.3秒ごとに4ダメージを与え炎上させる炎の輪を展開。周囲に4つの火の玉を射出。クールダウン12秒。",
    skillGravityName: "重力崩壊", skillGravityDesc: "敵を引き寄せて0.3秒ごとに2ダメージを与える特異点を生成。敵の弾を消滅させ、最後に6ダメの爆発を起こす。クールダウン13秒。",
    skillParryMasterName: "弾きの極意", skillParryMasterDesc: "5秒間、攻撃するだけで自動的にパリィが発動。クールダウン16秒。",
    btnShield: "加護",
    btnFlash: "瞬歩",
    btnFirewheel: "回天",
    btnGravity: "重力",
    btnParryMaster: "極意",
    screenShakeMode: "画面の揺れ",
    shakeOn: "標準",
    shakeReduced: "軽減",
    shakeOff: "オフ",
    autoUlt: "気の自動発動",
    autoUltOn: "オン",
    autoUltOff: "オフ",
    screenFlash: "フラッシュ・反転",
    weatherEffects: "天候と桜の花びら",
    speedLines: "スピードライン",
    floatingText: "ダメージ数値表示",
    groundScars: "地面の斬撃痕",
    settingsOn: "オン",
    settingsOff: "オフ",
    pvpLobbyTitle: "居合・対戦ロビー",
    pvpMyProfile: "マイプロフィール",
    pvpLoadingRonin: "浪人を読み込み中...",
    pvpSave: "保存",
    pvpUidDisplay: "UID: 読み込み中...",
    pvpCopy: "コピー",
    pvpSelectRules: "ゲームルールの選択",
    pvpClassicDuel: "クラシック決闘 (ライフ 3)",
    pvpSuddenDeath: "サドンデス (ライフ 1, 高速開始)",
    pvpHyperSpeed: "ハイスピード決闘 (ライフ 3, 急加速)",
    pvpStormGod: "雷神の暴風 (ライフ 3, 落雷発生)",
    pvpCoopSurvival: "悪夢 of 共同生存モード (インセイン難易度, AI群れ)",
    pvpSuddenDeathShort: "サドンデス",
    pvpHyperSpeedShort: "ハイスピード",
    pvpStormGodShort: "雷神の暴風",
    pvpCoopSurvivalShort: "共同生存",
    pvpFindMatch: "対戦相手を探す",
    pvpCancelQueue: "マッチングをキャンセル",
    pvpSearching: "対戦相手を検索中... ",
    pvpFoundConnecting: "対戦相手が見つかりました！接続中...",
    pvpFriends: "フレンド",
    pvpRequests: "リクエスト",
    pvpTopDuelists: "上位決闘者",
    pvpAddFriend: "フレンド追加",
    pvpFriendUidPlaceholder: "フレンドのUIDを貼り付け...",
    pvpAdd: "追加",
    pvpNoFriends: "フレンドがまだ追加されていません。UIDを共有しましょう！",
    pvpPendingRequests: "保留中のリクエスト",
    pvpNoRequests: "保留中のリクエストはありません。",
    pvpNoRecords: "まだ対戦記録がありません。",
    pvpLoadingLeaderboard: "リーダーボードを読み込み中...",
    pvpBackToMenu: "メニューに戻る",
    pvpReadyRoomMode: "モード: ",
    pvpHost: "ホスト (P1)",
    pvpClient: "クライアント (P2)",
    pvpWaiting: "待機中",
    pvpReady: "準備完了",
    pvpReadyUp: "準備完了",
    pvpCancelReady: "準備取消",
    pvpDisconnect: "切断する",
    pvpDuelChallenge: "決闘の申し込み！",
    pvpDecline: "辞退",
    pvpAccept: "受諾",
    pvpDefendTimedParry: "防御: タイミングよく弾け！",
    pvpWaitingForOpponent: "相手の行動を待っています...",
    pvpYourTurn: "あなたのターン: 攻撃長押しでチャージ",
    pvpParryLockout: "パリィ不可！",
    pvpWins: "勝利！",
    pvpRematch: "再戦",
    pvpRematchStatus: "再戦？ ({count}/2 準備完了)",
    pvpQuitToMenu: "タイトルへ",
    pvpRound: "ラウンド",
    pvpReadyText: "尋常に...",
    pvpRally: "ラリー:",
    pvpSpeed: "速度",
    pvpKills: "討伐数",
    pvpConnecting: "接続中...",
    pvpConnected: "接続完了",
    pvpError: "エラー",
    pvpOnline: "接続完了",
    pvpChallengeMsg: "{name}から決闘の申し込みが届きました！",
    pvpInvite: "招待",
    
    // Alert strings
    alertUidCopied: "UIDがクリップボードにコピーされました！",
    alertFailedToConnect: "接続に失敗しました: ",
    alertOpponentDisconnected: "対戦相手の接続が切れました。メインメニューに戻ります。",
    alertConnectionClosed: "対戦相手によって接続が切断されました。",
    alertFailedUpdateName: "表示名の更新に失敗しました: ",
    alertProfileNameUpdated: "プロフィール名が正常に更新されました！",
    alertFriendReqAccepted: "フレンドリクエストを受諾しました！",
    alertFailedAcceptReq: "リクエストの受諾に失敗しました: ",
    alertFriendReqDeclined: "フレンドリクエストを辞退しました。",
    alertFailedDeclineReq: "リクエストの辞退に失敗しました: ",
    alertEnterValidUid: "有効な8桁の数値のUIDを入力してください。",
    alertCannotAddSelf: "自分自身をフレンドに追加することはできません。",
    alertUidNotFound: "浪人UIDが見つかりません。",
    alertAlreadyFriends: "この浪人とは既にフレンドです。",
    alertFailedAddFriend: "フレンドの追加に失敗しました: ",
    alertFriendReqSent: "{name}にフレンドリクエストを送信しました！",
    alertFailedRemoveFriend: "フレンドの削除に失敗しました: ",
    alertFriendRemoved: "フレンドを削除しました。",
    alertDuelInviteDeclined: "決闘への招待が辞退されました。",
    alertFailedInviteFriend: "フレンドへの招待に失敗しました: ",
    alertMatchmakingFailed: "マッチングの接続に失敗しました: ",
    alertFailedMatchmaking: "マッチングへの参加に失敗しました: "
  }
};

export const loaderTips: Record<string, string[]> = {
  en: [
    "Dash at the exact moment of an enemy lunge to trigger a Perfect Dodge.",
    "Hold down SLASH to charge a piercing Iaijutsu Shockwave projectile.",
    "Release your charged slash right as an enemy strikes to Parry their attack.",
    "Basic attacks automatically snap to the nearest target within 600px range.",
    "Build FLOW via combo kills to activate your Ultimate time-slowed state.",
    "Dashing grants full invulnerability frames. Use it to escape tight corners.",
    "Level up to choose powerful modifiers like wind stance and giant katana.",
    "Keep combos active! Higher combos fill the Flow meter significantly faster."
  ],
  ja: [
    "敵の突進攻撃にタイミングを合わせて回避すると、ジャスト回避が発動します。",
    "攻撃ボタンを長押しすると、敵を貫通する「居合・真空波」をチャージできます。",
    "敵の攻撃を受ける瞬間にチャージを解放すると、攻撃をパリィできます。",
    "通常攻撃は、範囲600px以内の最も近い敵へ自動でホーミングします。",
    "コンボキルで気(FLOW)を最大まで溜めると、強力な奥義を発動できます。",
    "回避（ダッシュ）中は完全無敵です。敵に囲まれたときは迷わず使いましょう。",
    "レベルアップ時は、巨大化やクールダウン短縮などの強力な強化を選択できます。",
    "コンボを途切れさせないように！コンボ数が多いほど気が早く溜まります。"
  ]
};

export function registerAssetToLoad(img: HTMLImageElement) {
  globals.totalAssetsToLoad++;
  img.onload = onAssetLoaded;
  img.onerror = onAssetLoaded;
}

function onAssetLoaded() {
  globals.assetsLoadedCount++;
  assetCallbacks.onProgress();
}

function pad(n: number) { return n.toString().padStart(4, '0'); }

function loadAnim(folder: string, prefix: string, start: number, end: number) {
  const images: HTMLImageElement[] = [];
  for (let i = start; i <= end; i++) {
    const img = new Image();
    registerAssetToLoad(img);
    img.src = encodeURI(`sprites/Stick Figure Character Sprites 2D/${folder}/${prefix}_${pad(i)}.png`);
    images.push(img);
  }
  return images;
}

export const anims = {
  sword: {
    idle: loadAnim('Sword sprites', 'sword_Idle', 1, 8),
    walk: loadAnim('Sword sprites', 'sword_run', 17, 24),
    attack: loadAnim('Sword sprites', 'sword_combo', 65, 75),
    dash: loadAnim('Sword sprites', 'sword_dash', 33, 38),
    dead: loadAnim('Sword sprites', 'sword_death', 52, 61),
  },
  fighter: {
    idle: loadAnim('Fighter sprites', 'fighter_Idle', 1, 8),
    walk: loadAnim('Fighter sprites', 'fighter_run', 17, 24),
    attack: loadAnim('Fighter sprites', 'fighter_combo', 64, 75),
    dash: loadAnim('Fighter sprites', 'fighter_dash', 33, 38),
    dead: loadAnim('Fighter sprites', 'fighter_death', 52, 61),
  },
  pistol: {
    idle: loadAnim('Pistol sprites', 'pistol_Idle', 1, 8),
    walk: loadAnim('Pistol sprites', 'pistol_run', 17, 24),
    attack: loadAnim('Pistol sprites', 'pistol_shot', 64, 65),
    dash: loadAnim('Pistol sprites', 'pistol_dash', 33, 38),
    dead: loadAnim('Pistol sprites', 'pistol_death', 52, 61),
  }
};

export const bgLayers = [
  { name: 'sky', speed: 0.01 },
  { name: 'ruins_bg', speed: 0.05 },
  { name: 'hills&trees', speed: 0.1 },
  { name: 'ruins', speed: 0.2 },
  { name: 'ruins2', speed: 0.3 },
  { name: 'statue', speed: 0.4 },
  { name: 'stones&grass', speed: 0.6 }
];

export const bgImages: Record<string, HTMLImageElement> = {};
bgLayers.forEach(layer => {
  const img = new Image();
  registerAssetToLoad(img);
  img.src = `fantasy_bg/${encodeURIComponent(layer.name + '.png')}?v=2`;
  bgImages[layer.name] = img;
});

export const playerImages: Record<string, HTMLImageElement> = {};
Object.entries(svgAssets).forEach(([name, url]) => {
  const img = new Image();
  registerAssetToLoad(img);
  img.src = url;
  playerImages[name] = img;
});

export const skillsData = [
  { id: 'enhance', nameKey: 'skillEnhanceName', descKey: 'skillEnhanceDesc' },
  { id: 'shield', nameKey: 'skillShieldName', descKey: 'skillShieldDesc' },
  { id: 'dash', nameKey: 'skillDashName', descKey: 'skillDashDesc' },
  { id: 'firewheel', nameKey: 'skillFirewheelName', descKey: 'skillFirewheelDesc' },
  { id: 'gravity', nameKey: 'skillGravityName', descKey: 'skillGravityDesc' },
  { id: 'parry_master', nameKey: 'skillParryMasterName', descKey: 'skillParryMasterDesc' },
  { id: 'decoy_illusion', nameKey: 'skillDecoyName', descKey: 'skillDecoyDesc' }
];

function loadVfxFrames(pathPattern: string, count: number, startIdx = 1, padSize = 0) {
  const frames: HTMLImageElement[] = [];
  for (let i = 0; i < count; i++) {
    const frameNum = startIdx + i;
    const numStr = padSize > 0 ? frameNum.toString().padStart(padSize, '0') : frameNum.toString();
    const img = new Image();
    registerAssetToLoad(img);
    img.src = encodeURI(pathPattern.replace('{N}', numStr));
    frames.push(img);
  }
  return frames;
}

export const vfxAnims = {
  custom: {
    slash: loadVfxFrames('vfx/Frames/Slash_color5_frame{N}.png', 9, 1),
    dragonFury: loadVfxFrames('vfx/Dragon_fury/Slash_color4_frame{N}.png', 9, 1),
    invincible: loadVfxFrames('vfx/invincible/Starcaller_spell_3_frame_{N}.png', 15, 1),
    starfall: loadVfxFrames('vfx/starfall/Starcaller_spell_2_frame_{N}.png', 8, 1),
    vortex: loadVfxFrames('vfx/vortex/FireMage_skill3_frame{N}.png', 12, 1)
  },
  slashes: {
    slash1: {
      color1: loadVfxFrames('vfx/Pixel Art Animations - Slashes/128x128/Slash 1/color1/Frames/Slash_color1_frame{N}.png', 9, 1),
      color2: loadVfxFrames('vfx/Pixel Art Animations - Slashes/128x128/Slash 1/color2/Frames/Slash_color2_frame{N}.png', 9, 1),
      color3: loadVfxFrames('vfx/Pixel Art Animations - Slashes/128x128/Slash 1/color3/Frames/Slash_color3_frame{N}.png', 9, 1),
      color4: loadVfxFrames('vfx/Pixel Art Animations - Slashes/128x128/Slash 1/color4/Frames/Slash_color4_frame{N}.png', 9, 1),
      color5: loadVfxFrames('vfx/Pixel Art Animations - Slashes/128x128/Slash 1/color5/Frames/Slash_color5_frame{N}.png', 9, 1),
    },
    slash2: {
      color1: loadVfxFrames('vfx/Pixel Art Animations - Slashes/128x128/Slash 2/color1/Frames/Slash2_color1_frame{N}.png', 7, 1),
      color2: loadVfxFrames('vfx/Pixel Art Animations - Slashes/128x128/Slash 2/color2/Frames/Slash2_color2_frame{N}.png', 7, 1),
      color3: loadVfxFrames('vfx/Pixel Art Animations - Slashes/128x128/Slash 2/color3/Frames/Slash2_color3_frame{N}.png', 7, 1),
      color4: loadVfxFrames('vfx/Pixel Art Animations - Slashes/128x128/Slash 2/color4/Frames/Slash2_color4_frame{N}.png', 7, 1),
      color5: loadVfxFrames('vfx/Pixel Art Animations - Slashes/128x128/Slash 2/color5/Frames/Slash2_color5_frame{N}.png', 7, 1),
    },
    slash3: {
      color1: loadVfxFrames('vfx/Pixel Art Animations - Slashes/128x128/Slash 3/color1/Frames/Slash3_color1_frame{N}.png', 9, 1),
      color2: loadVfxFrames('vfx/Pixel Art Animations - Slashes/128x128/Slash 3/color2/Frames/Slash3_color2_frame{N}.png', 9, 1),
      color3: loadVfxFrames('vfx/Pixel Art Animations - Slashes/128x128/Slash 3/color3/Frames/Slash3_color3_frame{N}.png', 9, 1),
      color4: loadVfxFrames('vfx/Pixel Art Animations - Slashes/128x128/Slash 3/color4/Frames/Slash3_color4_frame{N}.png', 9, 1),
      color5: loadVfxFrames('vfx/Pixel Art Animations - Slashes/128x128/Slash 3/color5/Frames/Slash3_color5_frame{N}.png', 9, 1),
    }
  },
  auras: {
    arcane: loadVfxFrames('vfx/vfx/fx_pack_01/aura_fire_0004/arcane/128/frames/frame_{N}.png', 16, 0, 3),
    fire: loadVfxFrames('vfx/vfx/fx_pack_01/aura_fire_0004/fire/128/frames/frame_{N}.png', 16, 0, 3),
    ice: loadVfxFrames('vfx/vfx/fx_pack_01/aura_fire_0004/ice/128/frames/frame_{N}.png', 16, 0, 3),
    poison: loadVfxFrames('vfx/vfx/fx_pack_01/aura_fire_0004/poison/128/frames/frame_{N}.png', 16, 0, 3),
    holy: loadVfxFrames('vfx/vfx/fx_pack_01/aura_fire_0004/holy/128/frames/frame_{N}.png', 16, 0, 3)
  },
  explosions: {
    arcane: loadVfxFrames('vfx/vfx/fx_pack_01/explosion_fire_0000/arcane/128/frames/frame_{N}.png', 16, 0, 3),
    fire: loadVfxFrames('vfx/vfx/fx_pack_01/explosion_fire_0000/fire/128/frames/frame_{N}.png', 16, 0, 3),
    ice: loadVfxFrames('vfx/vfx/fx_pack_01/explosion_fire_0000/ice/128/frames/frame_{N}.png', 16, 0, 3),
    poison: loadVfxFrames('vfx/vfx/fx_pack_01/explosion_fire_0000/poison/128/frames/frame_{N}.png', 16, 0, 3),
    holy: loadVfxFrames('vfx/vfx/fx_pack_01/explosion_fire_0000/holy/128/frames/frame_{N}.png', 16, 0, 3)
  },
  impacts: {
    arcane: loadVfxFrames('vfx/vfx/fx_pack_01/impact_fire_0002/arcane/128/frames/frame_{N}.png', 16, 0, 3),
    fire: loadVfxFrames('vfx/vfx/fx_pack_01/impact_fire_0002/fire/128/frames/frame_{N}.png', 16, 0, 3),
    ice: loadVfxFrames('vfx/vfx/fx_pack_01/impact_fire_0002/ice/128/frames/frame_{N}.png', 16, 0, 3),
    poison: loadVfxFrames('vfx/vfx/fx_pack_01/impact_fire_0002/poison/128/frames/frame_{N}.png', 16, 0, 3),
    holy: loadVfxFrames('vfx/vfx/fx_pack_01/impact_fire_0002/holy/128/frames/frame_{N}.png', 16, 0, 3)
  },
  heals: {
    arcane: loadVfxFrames('vfx/vfx/fx_pack_01/heal_fire_0005/arcane/128/frames/frame_{N}.png', 16, 0, 3),
    fire: loadVfxFrames('vfx/vfx/fx_pack_01/heal_fire_0005/fire/128/frames/frame_{N}.png', 16, 0, 3),
    ice: loadVfxFrames('vfx/vfx/fx_pack_01/heal_fire_0005/ice/128/frames/frame_{N}.png', 16, 0, 3),
    poison: loadVfxFrames('vfx/vfx/fx_pack_01/heal_fire_0005/poison/128/frames/frame_{N}.png', 16, 0, 3),
    holy: loadVfxFrames('vfx/vfx/fx_pack_01/heal_fire_0005/holy/128/frames/frame_{N}.png', 16, 0, 3)
  },
  fireMage: {
    vfx1: loadVfxFrames('vfx/Pixel Art VFX - Fire Mage - FREE Version/VFX1/frames/FireMage_skill1_frame{N}.png', 7, 1),
    vfx2: loadVfxFrames('vfx/Pixel Art VFX - Fire Mage - FREE Version/VFX2/frames/FireMage_skill2_frame{N}.png', 12, 1),
    vfx3: loadVfxFrames('vfx/Pixel Art VFX - Fire Mage - FREE Version/VFX3/frames/FireMage_skill3_frame{N}.png', 12, 1)
  },
  frostKnight: {
    vfx1: loadVfxFrames('vfx/Pixel Art VFX - Frost Knight - FREE Version/VFX1/frames/FrostKnight_skill1_frame{N}.png', 14, 1),
    vfx2: loadVfxFrames('vfx/Pixel Art VFX - Frost Knight - FREE Version/VFX2/frames/FrostKnight_skill2_frame{N}.png', 9, 1),
    vfx3: loadVfxFrames('vfx/Pixel Art VFX - Frost Knight - FREE Version/VFX3/Frames/FrostKnight_skill3_frame{N}.png', 11, 1)
  },
  starcaller: {
    vfx1: loadVfxFrames('vfx/Pixel Art VFX - Starcaller - FREE Version/VFX 1/Frames/Starcaller_spell_1_frame_{N}.png', 7, 1),
    vfx2: loadVfxFrames('vfx/Pixel Art VFX - Starcaller - FREE Version/VFX 2/Frames/Starcaller_spell_2_frame_{N}.png', 8, 1),
    vfx3: loadVfxFrames('vfx/Pixel Art VFX - Starcaller - FREE Version/VFX 3/Frames/Starcaller_spell_3_frame_{N}.png', 15, 1)
  },
  warlock: {
    vfx1: loadVfxFrames('vfx/Pixel Art VFX - Warlock - FREE Version/VFX1/Frames/Warlock_skill1_frame{N}.png', 8, 1),
    vfx2: loadVfxFrames('vfx/Pixel Art VFX - Warlock - FREE Version/VFX2/Frames/Warlock_skill2_frame{N}.png', 13, 1),
    vfx3: loadVfxFrames('vfx/Pixel Art VFX - Warlock - FREE Version/VFX3/Frames/Warlock_skill3_frame{N}.png', 8, 1)
  }
};

